 # This is a basic workflow to help you get started with Actions

name: Discord-Sync

       # Controls when the workflow will run
on:
  # Triggers the workflow every 5 minutes
  schedule:
    # Run every day at 12:00am (UTC)
    - cron: '0 * * * *'

env:
  API_KEY: ${{ secrets.API_KEY }}
  API_USERNAME: ${{ secrets.API_USERNAME }}
  TOKEN: ${{ secrets.DH_PASS }}

 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "cron"
  cron:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run discord/Discourse Role sync
        run: node scripts/manual-sync.js 
